---
#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

############
# Env Vars #
############
env:
  jest: true
  node: true

###############
# Parser vars #
###############
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: script

###########
# Plugins #
###########
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
plugins:
  - '@typescript-eslint'
  - 'jest'
#########
# Rules #
#########
# rules:
